name: Linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: install modules
        run: npm ci --force
      - name: build production project
        run: npm run build:prod:ci
      - name: linting typescript
        if: always()
        run: npm run lint:ts
      - name: linting scss
        if: always()
        run: npm run lint:scss
      - name: running unit tests
        if: always()
        run: npm run test:unit
      - name: running screenshot testing
        if: always()
        run: npm run test:ui:ci